name: deploy

on:
  workflow_call:
    inputs:
      instance_id:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      instance_id:
        type: string
        required: true
        default: "bx"

env:
  instance_id: ${{ (inputs || github.event.inputs).instance_id }}
  environment: ${{
    (inputs || github.event.inputs).instance_id == 'uat' && 'UAT' ||
    contains((inputs || github.event.inputs).instance_id, 'ax') && 'DEV' ||
    (inputs || github.event.inputs).instance_id == 'bx' && 'DEV'||
    (inputs || github.event.inputs).instance_id == 'prod' && 'PROD'
    }}

jobs:
  Record_Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              environment: ${{ env.environment }},
              auto_merge: false,
              required_contexts: [],
              payload: JSON.stringify({ deployment_status: "success" })
            });
