name: deploy

on:
  workflow_call:
    inputs:
      instance_id:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      instance_id:
        type: string
        required: true
        default: "bx"

env:
  instance_id: ${{ (inputs || github.event.inputs).instance_id }}
  environment: ${{
    (inputs || github.event.inputs).instance_id == 'uat' && 'UAT' ||
    contains((inputs || github.event.inputs).instance_id, 'ax') && format('Dev-{0}', (inputs || github.event.inputs).instance_id) ||
    (inputs || github.event.inputs).instance_id == 'bx' && format('Dev-{0}', (inputs || github.event.inputs).instance_id) ||
    (inputs || github.event.inputs).instance_id
    }}

jobs:
  Record_Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${{ github.ref }}`,
              environment: `${{ env.environment }}`,
              auto_merge: false,
              required_contexts: [],
              payload: JSON.stringify({ deployment_status: "success" })
            });
